[platformio]
src_dir = .
include_dir = .
default_envs = base
  
[env:base]
platform = ststm32
platform_packages = toolchain-gccarmnoneeabi@~1.120301.0
upload_protocol = stlink
monitor_speed = 115200

board = stm32c092
board_build.ldscript = STM32C092XX_FLASH.ld

lib_deps =
    https://github.com/eagletrt/libeagletrt-sw#v0.1.0
    # https://github.com/eagletrt/libspec-sw#v1.0.0

build_flags = 
    -DUSE_HAL_DRIVER
    -Wall 
    -Wextra 
    -Wpedantic 
    # -Werror
    -ICore/Inc
    -ICore/Inc/bms/
    -ICore/Inc/common/
    -IDrivers/CMSIS/Include/
    -IDrivers/STM32C0xx_HAL_Driver/Inc/
    -IDrivers/CMSIS/Device/ST/STM32C0xx/Include/
build_src_filter =
    +<Core/Src/>
    +<Drivers/STM32C0xx_HAL_Driver/Src/>
    -<Drivers/STM32C0xx_HAL_Driver/Src/*_template.c>
    +<./startup_stm32c092xx.s>

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*
    clangtidy: --warnings-as-errors=*
    clangtidy: --header-filter=Core/Inc/.*
check_src_filters =
    -<**>
    +<Core/Src/**>
    +<Core/Inc/**>

[env:native]
platform = native
test_framework = unity
test_build_src = true

lib_deps =
    https://github.com/eagletrt/libeagletrt-sw#v0.1.0

build_flags =
    -DEAGLETRT_STATIC= 
    -DEAGLETRT_STATIC_INLINE=
    -DCONFIG_TEMPERATURE_MODULE_ENABLE
    -ICore/Inc/bms/
    -ICore/Inc/common/
build_src_filter =
    +<Core/Src/bms/>
