/******************************************************************************
Finite State Machine
Project: assets/fsm/fsm.dot
Description: gv_fsm example

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-04-27 14:29:37 +0200
Generated from: assets/fsm/fsm.dot
The finite state machine has:
  5 states
  10 transition functions

******************************************************************************/

#ifndef FSM_H
#define FSM_H
#ifdef __cplusplus
extern "C" {
#endif
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include "defines.h"
#include "types.h"

struct FsmData {
    uint32_t tick;
};

/*!
 * \brief            Everything the FSM wants to report that is measured by the
 *                   board rather than by one of the abstract modules.
 *
 * \details          The FSM must not reach into the peripheral drivers, so the
 *                   board layer fills this in through
 *                   #fsm_read_board_measurements_callback and the FSM only ever
 *                   reads plain numbers out of it.
 */
struct FsmBoardMeasurements {
    volt vdda;                                  /*!< Analog supply measured through VREFINT in V */
    celsius mcu_temperature;                    /*!< MCU die temperature in °C */
    volt vin;                                   /*!< Fused input voltage in V */
    volt vin_unfused;                           /*!< Unfused input voltage in V */
    volt vsup;                                  /*!< Supply voltage in V */
    volt vout;                                  /*!< Output voltage in V */
    volt lvms_out;                              /*!< LVMS output voltage in V */
    volt mcu_5v;                                /*!< 5 V rail voltage in V */
    volt charger_voltage;                       /*!< Charger voltage in V */
    ampere charger_current;                     /*!< Charger current in A */
    volt i_out_sense;                           /*!< Output current sense node in V */
    size_t ntc_mux_channel;                     /*!< Multiplexer channel currently selected */
    bool ntc_mux_held;                          /*!< True while the multiplexer is pinned for debugging */
    volt ntc_voltages[DEFINES_CELLS_NTC_COUNT]; /*!< Last raw NTC voltage of each channel in V */
};

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
typedef void state_data_t;

/*!
 * \brief            Callback returning the current tick in ms.
 */
typedef uint32_t (*fsm_get_tick_callback)(void);

/*!
 * \brief            Callback opening or closing the master output relay.
 *
 * \param[in]        closed True to connect the output, false to release it.
 */
typedef void (*fsm_set_master_relay_callback)(bool closed);

/*!
 * \brief            Callback filling a snapshot of the board measurements.
 *
 * \param[out]       out The snapshot to populate.
 */
typedef void (*fsm_read_board_measurements_callback)(struct FsmBoardMeasurements *out);

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
    STATE_INIT = 0,
    STATE_IDLE,
    STATE_FATAL,
    STATE_FLASH,
    STATE_BALANCING,
    NUM_STATES,
    NO_CHANGE
} state_t;

// State human-readable names
extern const char *state_names[];

// State function and state transition prototypes
typedef state_t state_func_t(state_data_t *data);
typedef void transition_func_t(state_data_t *data);

// State functions
// Function to be executed in state init
// valid return states: STATE_IDLE, STATE_FATAL
state_t do_init(state_data_t *data);
// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_FLASH, STATE_IDLE, STATE_BALANCING, STATE_FATAL
state_t do_idle(state_data_t *data);
// Function to be executed in state fatal
// valid return states: NO_CHANGE, STATE_FLASH, STATE_FATAL
state_t do_fatal(state_data_t *data);
// Function to be executed in state flash
// valid return states: STATE_IDLE, STATE_FATAL
state_t do_flash(state_data_t *data);
// Function to be executed in state balancing
// valid return states: NO_CHANGE, STATE_IDLE, STATE_BALANCING, STATE_FATAL
state_t do_balancing(state_data_t *data);

// List of state functions
extern state_func_t *const state_table[NUM_STATES];

// Transition functions
void init_to_idle(state_data_t *data);
void init_to_fatal(state_data_t *data);
void flash_to_idle(state_data_t *data);
void flash_to_fatal(state_data_t *data);
void idle_to_flash(state_data_t *data);
void idle_to_balancing(state_data_t *data);
void idle_to_fatal(state_data_t *data);
void balancing_to_idle(state_data_t *data);
void balancing_to_fatal(state_data_t *data);
void fatal_to_flash(state_data_t *data);

// Table of transition functions
extern transition_func_t *const transition_table[NUM_STATES][NUM_STATES];

// state manager
state_t run_state(state_t cur_state, state_data_t *data);

#ifdef __cplusplus
}
#endif
#endif // FSM_H
