/******************************************************************************
Finite State Machine
Project: bms_monitor_fsm
Description: Bms Monitor FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.4
Generation date: 2026-08-12 20:36:26 +0200
Generated from: bms_monitor_fsm.dot
The finite state machine has:
  22 states
  1 transition functions
Functions and types have been generated with prefix "bms_monitor_fsm_"
******************************************************************************/

#include "bms-monitor-fsm.h"

/*** USER CODE BEGIN MACROS ***/
#include <string.h>

#include "bms-monitor-api.h"
#include "eagletrt-api.h"
#include "logger-api.h"

/*!
 * \brief Diagnostic helper: run a bms_monitor_api_* call and emit a WARN log
 *        line if it does not return BMS_MONITOR_RC_OK.
 * \details Added to surface the return codes that the generated state bodies
 *        would otherwise discard with a (void) cast. \p label identifies the
 *        FSM step so a failure can be traced back to the exact SPI operation.
 */
#define BMS_MON_STEP(call, label)                                                     \
    do {                                                                              \
        const enum BmsMonitorReturnCode _mon_rc = (call);                             \
        if (_mon_rc != BMS_MONITOR_RC_OK) {                                           \
            logger_api_log(LOGGER_LEVEL_WARN, "[MON] " label " rc=%d", (int)_mon_rc); \
        }                                                                             \
    } while (0)
/*** USER CODE END MACROS ***/

// GLOBALS
// State human-readable names
const char *bms_monitor_fsm_state_names[] = { "init", "start_volt_conversion", "volt_write_configuration", "volt_read_configuration", "read_volt_a", "read_volt_b", "start_temp_conversion", "temp_write_configuration", "temp_read_configuration", "read_temp_a", "start_open_wire_pup_conversion_first", "open_wire_pup_write_configuration", "start_open_wire_pup_conversion_second", "open_wire_pup_read_configuration", "read_open_wire_pup_a", "read_open_wire_pup_b", "start_open_wire_pud_conversion_first", "open_wire_pud_write_configuration", "start_open_wire_pud_conversion_second", "open_wire_pud_read_configuration", "read_open_wire_pud_a", "read_open_wire_pud_b" };

// List of state functions
bms_monitor_fsm_state_func_t *const bms_monitor_fsm_state_table[BMS_MONITOR_FSM_NUM_STATES] = {
    bms_monitor_fsm_do_init,                                  // in state init
    bms_monitor_fsm_do_start_volt_conversion,                 // in state start_volt_conversion
    bms_monitor_fsm_do_volt_write_configuration,              // in state volt_write_configuration
    bms_monitor_fsm_do_volt_read_configuration,               // in state volt_read_configuration
    bms_monitor_fsm_do_read_volt_a,                           // in state read_volt_a
    bms_monitor_fsm_do_read_volt_b,                           // in state read_volt_b
    bms_monitor_fsm_do_start_temp_conversion,                 // in state start_temp_conversion
    bms_monitor_fsm_do_temp_write_configuration,              // in state temp_write_configuration
    bms_monitor_fsm_do_temp_read_configuration,               // in state temp_read_configuration
    bms_monitor_fsm_do_read_temp_a,                           // in state read_temp_a
    bms_monitor_fsm_do_start_open_wire_pup_conversion_first,  // in state start_open_wire_pup_conversion_first
    bms_monitor_fsm_do_open_wire_pup_write_configuration,     // in state open_wire_pup_write_configuration
    bms_monitor_fsm_do_start_open_wire_pup_conversion_second, // in state start_open_wire_pup_conversion_second
    bms_monitor_fsm_do_open_wire_pup_read_configuration,      // in state open_wire_pup_read_configuration
    bms_monitor_fsm_do_read_open_wire_pup_a,                  // in state read_open_wire_pup_a
    bms_monitor_fsm_do_read_open_wire_pup_b,                  // in state read_open_wire_pup_b
    bms_monitor_fsm_do_start_open_wire_pud_conversion_first,  // in state start_open_wire_pud_conversion_first
    bms_monitor_fsm_do_open_wire_pud_write_configuration,     // in state open_wire_pud_write_configuration
    bms_monitor_fsm_do_start_open_wire_pud_conversion_second, // in state start_open_wire_pud_conversion_second
    bms_monitor_fsm_do_open_wire_pud_read_configuration,      // in state open_wire_pud_read_configuration
    bms_monitor_fsm_do_read_open_wire_pud_a,                  // in state read_open_wire_pud_a
    bms_monitor_fsm_do_read_open_wire_pud_b,                  // in state read_open_wire_pud_b
};

// Table of transition functions
transition_func_t *const bms_monitor_fsm_transition_table[BMS_MONITOR_FSM_NUM_STATES][BMS_MONITOR_FSM_NUM_STATES] = {
    /* states:                                   init                           , start_volt_conversion          , volt_write_configuration       , volt_read_configuration        , read_volt_a                    , read_volt_b                    , start_temp_conversion          , temp_write_configuration       , temp_read_configuration        , read_temp_a                    , start_open_wire_pup_conversion_first, open_wire_pup_write_configuration, start_open_wire_pup_conversion_second, open_wire_pup_read_configuration, read_open_wire_pup_a           , read_open_wire_pup_b           , start_open_wire_pud_conversion_first, open_wire_pud_write_configuration, start_open_wire_pud_conversion_second, open_wire_pud_read_configuration, read_open_wire_pud_a           , read_open_wire_pud_b            */
    /* init                                  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_volt_conversion                 */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* volt_write_configuration              */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* volt_read_configuration               */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_volt_a                           */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_volt_b                           */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_temp_conversion                 */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* temp_write_configuration              */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* temp_read_configuration               */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_temp_a                           */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_open_wire_pup_conversion_first  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* open_wire_pup_write_configuration     */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_open_wire_pup_conversion_second */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* open_wire_pup_read_configuration      */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_open_wire_pup_a                  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_open_wire_pup_b                  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_open_wire_pud_conversion_first  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* open_wire_pud_write_configuration     */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_open_wire_pud_conversion_second */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* open_wire_pud_read_configuration      */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_open_wire_pud_a                  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_open_wire_pud_b                  */ { NULL, bms_monitor_fsm_check_open_wire, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
};

// Triggered event
bms_monitor_fsm_event_data_t *bms_monitor_fsm_fired_event = NULL;

/*** USER CODE BEGIN GLOBALS ***/
EAGLETRT_STATIC struct BmsMonitorFsmHandler bms_monitor_fsm_handler;
/*** USER CODE END GLOBALS ***/

// Function to check if an event has fired
bool bms_monitor_fsm_is_event_triggered() {
    return bms_monitor_fsm_fired_event != NULL;
}

// Function to trigger an event
void bms_monitor_fsm_event_trigger(bms_monitor_fsm_event_data_t *event) {
    if (bms_monitor_fsm_fired_event != NULL) {
        return;
    }
    bms_monitor_fsm_fired_event = event ? event : &(bms_monitor_fsm_event_data_t){};
}

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION
bms_monitor_fsm_state_t bms_monitor_fsm_do_init(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION;

    /*** USER CODE BEGIN DO_INIT ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END DO_INIT ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_volt_conversion
// valid return states: BMS_MONITOR_FSM_STATE_VOLT_WRITE_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_volt_conversion(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_VOLT_WRITE_CONFIGURATION;

    /*** USER CODE BEGIN DO_START_VOLT_CONVERSION ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_volt_conversion(), "start_volt_conversion");

    /*** USER CODE END DO_START_VOLT_CONVERSION ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_VOLT_WRITE_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state volt_write_configuration
// valid return states: BMS_MONITOR_FSM_STATE_VOLT_READ_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_volt_write_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_VOLT_READ_CONFIGURATION;

    /*** USER CODE BEGIN DO_VOLT_WRITE_CONFIGURATION ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_write_configuration(), "volt_write_configuration");

    /*** USER CODE END DO_VOLT_WRITE_CONFIGURATION ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_VOLT_READ_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state volt_read_configuration
// valid return states: BMS_MONITOR_FSM_STATE_READ_VOLT_A
bms_monitor_fsm_state_t bms_monitor_fsm_do_volt_read_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_VOLT_A;

    /*** USER CODE BEGIN DO_VOLT_READ_CONFIGURATION ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_configuration(), "volt_read_configuration");

    /*** USER CODE END DO_VOLT_READ_CONFIGURATION ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_VOLT_A:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_volt_a
// valid return states: BMS_MONITOR_FSM_STATE_READ_VOLT_B
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_volt_a(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_VOLT_B;

    /*** USER CODE BEGIN DO_READ_VOLT_A ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_voltages(BMS_MONITOR_VOLTAGE_REGISTER_A), "read_volt_a");

    /*** USER CODE END DO_READ_VOLT_A ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_VOLT_B:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_volt_b
// valid return states: BMS_MONITOR_FSM_STATE_START_TEMP_CONVERSION
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_volt_b(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_TEMP_CONVERSION;

    /*** USER CODE BEGIN DO_READ_VOLT_B ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_voltages(BMS_MONITOR_VOLTAGE_REGISTER_B), "read_volt_b");

    /*** USER CODE END DO_READ_VOLT_B ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_TEMP_CONVERSION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_temp_conversion
// valid return states: BMS_MONITOR_FSM_STATE_TEMP_WRITE_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_temp_conversion(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_TEMP_WRITE_CONFIGURATION;

    /*** USER CODE BEGIN DO_START_TEMP_CONVERSION ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_gpio_conversion(), "start_temp_conversion");

    /*** USER CODE END DO_START_TEMP_CONVERSION ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_TEMP_WRITE_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state temp_write_configuration
// valid return states: BMS_MONITOR_FSM_STATE_TEMP_READ_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_temp_write_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_TEMP_READ_CONFIGURATION;

    /*** USER CODE BEGIN DO_TEMP_WRITE_CONFIGURATION ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_write_configuration(), "temp_write_configuration");

    /*** USER CODE END DO_TEMP_WRITE_CONFIGURATION ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_TEMP_READ_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state temp_read_configuration
// valid return states: BMS_MONITOR_FSM_STATE_READ_TEMP_A
bms_monitor_fsm_state_t bms_monitor_fsm_do_temp_read_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_TEMP_A;

    /*** USER CODE BEGIN DO_TEMP_READ_CONFIGURATION ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_configuration(), "temp_read_configuration");

    /*** USER CODE END DO_TEMP_READ_CONFIGURATION ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_TEMP_A:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_temp_a
// valid return states: BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_FIRST
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_temp_a(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_FIRST;

    /*** USER CODE BEGIN DO_READ_TEMP_A ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_sample_gpios(), "read_temp_a");

    /*** USER CODE END DO_READ_TEMP_A ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_FIRST:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_open_wire_pup_conversion_first
// valid return states: BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_WRITE_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_open_wire_pup_conversion_first(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_WRITE_CONFIGURATION;

    /*** USER CODE BEGIN DO_START_OPEN_WIRE_PUP_CONVERSION_FIRST ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_open_wire_conversion(LTC6810_2_PUP_ACTIVE), "ow_pup_conv_first");

    /*** USER CODE END DO_START_OPEN_WIRE_PUP_CONVERSION_FIRST ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_WRITE_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state open_wire_pup_write_configuration
// valid return states: BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_SECOND
bms_monitor_fsm_state_t bms_monitor_fsm_do_open_wire_pup_write_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_SECOND;

    /*** USER CODE BEGIN DO_OPEN_WIRE_PUP_WRITE_CONFIGURATION ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_write_configuration(), "ow_pup_write_configuration");

    /*** USER CODE END DO_OPEN_WIRE_PUP_WRITE_CONFIGURATION ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_SECOND:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_open_wire_pup_conversion_second
// valid return states: BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_READ_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_open_wire_pup_conversion_second(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_READ_CONFIGURATION;

    /*** USER CODE BEGIN DO_START_OPEN_WIRE_PUP_CONVERSION_SECOND ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_open_wire_conversion(LTC6810_2_PUP_ACTIVE), "ow_pup_conv_second");

    /*** USER CODE END DO_START_OPEN_WIRE_PUP_CONVERSION_SECOND ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_READ_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state open_wire_pup_read_configuration
// valid return states: BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_A
bms_monitor_fsm_state_t bms_monitor_fsm_do_open_wire_pup_read_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_A;

    /*** USER CODE BEGIN DO_OPEN_WIRE_PUP_READ_CONFIGURATION ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_configuration(), "ow_pup_read_configuration");

    /*** USER CODE END DO_OPEN_WIRE_PUP_READ_CONFIGURATION ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_A:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_open_wire_pup_a
// valid return states: BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_B
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_open_wire_pup_a(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_B;

    /*** USER CODE BEGIN DO_READ_OPEN_WIRE_PUP_A ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_open_wire_voltages(BMS_MONITOR_VOLTAGE_REGISTER_A, BMS_MANAGER_OPEN_WIRE_OPERATION_PUP), "read_ow_pup_a");

    /*** USER CODE END DO_READ_OPEN_WIRE_PUP_A ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_B:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_open_wire_pup_b
// valid return states: BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_FIRST
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_open_wire_pup_b(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_FIRST;

    /*** USER CODE BEGIN DO_READ_OPEN_WIRE_PUP_B ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_open_wire_voltages(BMS_MONITOR_VOLTAGE_REGISTER_B, BMS_MANAGER_OPEN_WIRE_OPERATION_PUP), "read_ow_pup_b");

    /*** USER CODE END DO_READ_OPEN_WIRE_PUP_B ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_FIRST:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_open_wire_pud_conversion_first
// valid return states: BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_WRITE_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_open_wire_pud_conversion_first(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_WRITE_CONFIGURATION;

    /*** USER CODE BEGIN DO_START_OPEN_WIRE_PUD_CONVERSION_FIRST ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_open_wire_conversion(LTC6810_2_PUP_INACTIVE), "ow_pud_conv_first");

    /*** USER CODE END DO_START_OPEN_WIRE_PUD_CONVERSION_FIRST ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_WRITE_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state open_wire_pud_write_configuration
// valid return states: BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_SECOND
bms_monitor_fsm_state_t bms_monitor_fsm_do_open_wire_pud_write_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_SECOND;

    /*** USER CODE BEGIN DO_OPEN_WIRE_PUD_WRITE_CONFIGURATION ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_open_wire_conversion(LTC6810_2_PUP_INACTIVE), "ow_pud_conv_first");

    /*** USER CODE END DO_OPEN_WIRE_PUD_WRITE_CONFIGURATION ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_SECOND:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_open_wire_pud_conversion_second
// valid return states: BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_READ_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_open_wire_pud_conversion_second(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_READ_CONFIGURATION;

    /*** USER CODE BEGIN DO_START_OPEN_WIRE_PUD_CONVERSION_SECOND ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_open_wire_conversion(LTC6810_2_PUP_INACTIVE), "ow_pud_conv_second");

    /*** USER CODE END DO_START_OPEN_WIRE_PUD_CONVERSION_SECOND ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_READ_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state open_wire_pud_read_configuration
// valid return states: BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_A
bms_monitor_fsm_state_t bms_monitor_fsm_do_open_wire_pud_read_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_A;

    /*** USER CODE BEGIN DO_OPEN_WIRE_PUD_READ_CONFIGURATION ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_configuration(), "ow_pud_read_configuration");

    /*** USER CODE END DO_OPEN_WIRE_PUD_READ_CONFIGURATION ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_A:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_open_wire_pud_a
// valid return states: BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_B
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_open_wire_pud_a(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_B;

    /*** USER CODE BEGIN DO_READ_OPEN_WIRE_PUD_A ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_open_wire_voltages(BMS_MONITOR_VOLTAGE_REGISTER_A, BMS_MANAGER_OPEN_WIRE_OPERATION_PUD), "read_ow_pud_a");

    /*** USER CODE END DO_READ_OPEN_WIRE_PUD_A ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_B:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_open_wire_pud_b
// valid return states: BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_open_wire_pud_b(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION;

    /*** USER CODE BEGIN DO_READ_OPEN_WIRE_PUD_B ***/

    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_open_wire_voltages(BMS_MONITOR_VOLTAGE_REGISTER_B, BMS_MANAGER_OPEN_WIRE_OPERATION_PUD), "read_ow_pud_b");

    /*** USER CODE END DO_READ_OPEN_WIRE_PUD_B ***/

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from read_open_wire_pud_b to start_volt_conversion
void bms_monitor_fsm_check_open_wire(bms_monitor_fsm_state_data_t *data) {

    /*** USER CODE BEGIN CHECK_OPEN_WIRE ***/

    EAGLETRT_API_UNUSED(data);

    /*** USER CODE END CHECK_OPEN_WIRE ***/
}

/*  ____  _        _        
 * / ___|| |_ __ _| |_ ___  
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/ 
 * |____/ \__\__,_|\__\___| 
 *                          
 *                                              
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |   
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
 *                              |___/           
 */

bms_monitor_fsm_state_t bms_monitor_fsm_run_state(bms_monitor_fsm_state_t cur_state, bms_monitor_fsm_state_data_t *data) {

    /*** USER CODE BEGIN RUN_STATE ***/

    /*** USER CODE END RUN_STATE ***/

    bms_monitor_fsm_event_data_t *prev_ev = bms_monitor_fsm_fired_event;
    bms_monitor_fsm_state_t new_state = bms_monitor_fsm_state_table[cur_state](data);
    // Reset event status
    if (prev_ev != NULL) {
        bms_monitor_fsm_fired_event = NULL;
    }
    if (new_state == BMS_MONITOR_FSM_NO_CHANGE) {
        new_state = cur_state;
    }
    transition_func_t *transition = bms_monitor_fsm_transition_table[cur_state][new_state];
    if (transition) {
        transition(data);
    }
    return new_state;
}

/*** USER CODE BEGIN FUNCTIONS ***/

/*** USER CODE END FUNCTIONS ***/

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    bms_monitor_fsm_state_t cur_state = BMS_MONITOR_FSM_STATE_INIT;
    do {
        cur_state = bms_monitor_fsm_run_state(cur_state, NULL);
        sleep(1);
    } while (1);
    return 0;
}
#endif
