/******************************************************************************
Finite State Machine
Project: bms_monitor_fsm
Description: BMS monitor FSM

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-08-08 21:36:39 +0200
Generated from: ../lv-bms-sw/assets/bms_monitor_fsm/bms_monitor_fsm.dot
The finite state machine has:
  18 states
  1 transition functions

Functions and types have been generated with prefix "bms_monitor_fsm_"

******************************************************************************/

#include "bms-monitor-fsm.h"

/*** USER CODE BEGIN MACROS ***/

#include <string.h>

#include "bms-monitor-api.h"
#include "eagletrt-api.h"
#include "logger-api.h"

/*!
 * \brief Diagnostic helper: run a bms_monitor_api_* call and emit a WARN log
 *        line if it does not return BMS_MONITOR_RC_OK.
 * \details Added to surface the return codes that the generated state bodies
 *        would otherwise discard with a (void) cast. \p label identifies the
 *        FSM step so a failure can be traced back to the exact SPI operation.
 */
#define BMS_MON_STEP(call, label)                                                     \
    do {                                                                              \
        const enum BmsMonitorReturnCode _mon_rc = (call);                             \
        if (_mon_rc != BMS_MONITOR_RC_OK) {                                           \
            logger_api_log(LOGGER_LEVEL_WARN, "[MON] " label " rc=%d", (int)_mon_rc); \
        }                                                                             \
    } while (0)

/*** USER CODE END MACROS ***/

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// GLOBALS
// State human-readable names
const char *bms_monitor_fsm_state_names[] = { "init", "start_volt_conversion", "volt_write_configuration", "volt_read_configuration", "read_volt_a", "read_volt_b", "start_open_wire_pup_conversion_first", "open_wire_pup_write_configuration", "start_open_wire_pup_conversion_second", "open_wire_pup_read_configuration", "read_open_wire_pup_a", "read_open_wire_pup_b", "start_open_wire_pud_conversion_first", "open_wire_pud_write_configuration", "start_open_wire_pud_conversion_second", "open_wire_pud_read_configuration", "read_open_wire_pud_a", "read_open_wire_pud_b" };

// List of state functions
bms_monitor_fsm_state_func_t *const bms_monitor_fsm_state_table[BMS_MONITOR_FSM_NUM_STATES] = {
    bms_monitor_fsm_do_init,                                  // in state init
    bms_monitor_fsm_do_start_volt_conversion,                 // in state start_volt_conversion
    bms_monitor_fsm_do_volt_write_configuration,              // in state volt_write_configuration
    bms_monitor_fsm_do_volt_read_configuration,               // in state volt_read_configuration
    bms_monitor_fsm_do_read_volt_a,                           // in state read_volt_a
    bms_monitor_fsm_do_read_volt_b,                           // in state read_volt_b
    bms_monitor_fsm_do_start_open_wire_pup_conversion_first,  // in state start_open_wire_pup_conversion_first
    bms_monitor_fsm_do_open_wire_pup_write_configuration,     // in state open_wire_pup_write_configuration
    bms_monitor_fsm_do_start_open_wire_pup_conversion_second, // in state start_open_wire_pup_conversion_second
    bms_monitor_fsm_do_open_wire_pup_read_configuration,      // in state open_wire_pup_read_configuration
    bms_monitor_fsm_do_read_open_wire_pup_a,                  // in state read_open_wire_pup_a
    bms_monitor_fsm_do_read_open_wire_pup_b,                  // in state read_open_wire_pup_b
    bms_monitor_fsm_do_start_open_wire_pud_conversion_first,  // in state start_open_wire_pud_conversion_first
    bms_monitor_fsm_do_open_wire_pud_write_configuration,     // in state open_wire_pud_write_configuration
    bms_monitor_fsm_do_start_open_wire_pud_conversion_second, // in state start_open_wire_pud_conversion_second
    bms_monitor_fsm_do_open_wire_pud_read_configuration,      // in state open_wire_pud_read_configuration
    bms_monitor_fsm_do_read_open_wire_pud_a,                  // in state read_open_wire_pud_a
    bms_monitor_fsm_do_read_open_wire_pud_b,                  // in state read_open_wire_pud_b
};

// Table of transition functions
bms_monitor_fsm_transition_func_t *const bms_monitor_fsm_transition_table[BMS_MONITOR_FSM_NUM_STATES][BMS_MONITOR_FSM_NUM_STATES] = {
    /* states:                                   init                           , start_volt_conversion          , volt_write_configuration       , volt_read_configuration        , read_volt_a                    , read_volt_b                    , start_open_wire_pup_conversion_first, open_wire_pup_write_configuration, start_open_wire_pup_conversion_second, open_wire_pup_read_configuration, read_open_wire_pup_a           , read_open_wire_pup_b           , start_open_wire_pud_conversion_first, open_wire_pud_write_configuration, start_open_wire_pud_conversion_second, open_wire_pud_read_configuration, read_open_wire_pud_a           , read_open_wire_pud_b            */
    /* init                                  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_volt_conversion                 */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* volt_write_configuration              */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* volt_read_configuration               */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_volt_a                           */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_volt_b                           */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_open_wire_pup_conversion_first  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* open_wire_pup_write_configuration     */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_open_wire_pup_conversion_second */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* open_wire_pup_read_configuration      */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_open_wire_pup_a                  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_open_wire_pup_b                  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_open_wire_pud_conversion_first  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* open_wire_pud_write_configuration     */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* start_open_wire_pud_conversion_second */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* open_wire_pud_read_configuration      */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_open_wire_pud_a                  */ { NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
    /* read_open_wire_pud_b                  */ { NULL, bms_monitor_fsm_check_open_wire, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL },
};

/*** USER CODE BEGIN GLOBALS ***/

EAGLETRT_STATIC struct BmsMonitorFsmHandler bms_monitor_fsm_handler;

/*** USER CODE END GLOBALS ***/

/*** USER CODE BEGIN ***/

bms_monitor_fsm_state_t bms_monitor_fsm_get_current_state(void) {
    return bms_monitor_fsm_handler.fsm_state;
}

/*** USER CODE END ***/

/*  ____  _        _
 * / ___|| |_ __ _| |_ ___
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *
 *   __                  _   _
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION
bms_monitor_fsm_state_t bms_monitor_fsm_do_init(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_volt_conversion
// valid return states: BMS_MONITOR_FSM_STATE_VOLT_WRITE_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_volt_conversion(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_VOLT_WRITE_CONFIGURATION;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_volt_conversion(), "start_volt_conversion");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_VOLT_WRITE_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state volt_write_configuration
// valid return states: BMS_MONITOR_FSM_STATE_VOLT_READ_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_volt_write_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_VOLT_READ_CONFIGURATION;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_write_configuration(), "volt_write_configuration");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_VOLT_READ_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state volt_read_configuration
// valid return states: BMS_MONITOR_FSM_STATE_READ_VOLT_A
bms_monitor_fsm_state_t bms_monitor_fsm_do_volt_read_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_VOLT_A;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_configuration(), "volt_read_configuration");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_VOLT_A:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_volt_a
// valid return states: BMS_MONITOR_FSM_STATE_READ_VOLT_B
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_volt_a(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_VOLT_B;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_voltages(BMS_MONITOR_VOLTAGE_REGISTER_A), "read_volt_a");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_VOLT_B:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_volt_b
// valid return states: BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_FIRST
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_volt_b(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_FIRST;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_voltages(BMS_MONITOR_VOLTAGE_REGISTER_B), "read_volt_b");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_FIRST:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_open_wire_pup_conversion_first
// valid return states: BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_WRITE_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_open_wire_pup_conversion_first(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_WRITE_CONFIGURATION;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_open_wire_conversion(LTC6810_2_PUP_ACTIVE), "ow_pup_conv_first");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_WRITE_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state open_wire_pup_write_configuration
// valid return states: BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_SECOND
bms_monitor_fsm_state_t bms_monitor_fsm_do_open_wire_pup_write_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_SECOND;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_write_configuration(), "ow_pup_write_configuration");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUP_CONVERSION_SECOND:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_open_wire_pup_conversion_second
// valid return states: BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_READ_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_open_wire_pup_conversion_second(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_READ_CONFIGURATION;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_open_wire_conversion(LTC6810_2_PUP_ACTIVE), "ow_pup_conv_second");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUP_READ_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state open_wire_pup_read_configuration
// valid return states: BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_A
bms_monitor_fsm_state_t bms_monitor_fsm_do_open_wire_pup_read_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_A;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_configuration(), "ow_pup_read_configuration");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_A:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_open_wire_pup_a
// valid return states: BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_B
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_open_wire_pup_a(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_B;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_open_wire_voltages(BMS_MONITOR_VOLTAGE_REGISTER_A, BMS_MANAGER_OPEN_WIRE_OPERATION_PUP), "read_ow_pup_a");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUP_B:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_open_wire_pup_b
// valid return states: BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_FIRST
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_open_wire_pup_b(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_FIRST;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_open_wire_voltages(BMS_MONITOR_VOLTAGE_REGISTER_B, BMS_MANAGER_OPEN_WIRE_OPERATION_PUP), "read_ow_pup_b");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_FIRST:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_open_wire_pud_conversion_first
// valid return states: BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_WRITE_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_open_wire_pud_conversion_first(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_WRITE_CONFIGURATION;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_open_wire_conversion(LTC6810_2_PUP_INACTIVE), "ow_pud_conv_first");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_WRITE_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state open_wire_pud_write_configuration
// valid return states: BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_SECOND
bms_monitor_fsm_state_t bms_monitor_fsm_do_open_wire_pud_write_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_SECOND;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_write_configuration(), "ow_pud_write_configuration");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_OPEN_WIRE_PUD_CONVERSION_SECOND:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state start_open_wire_pud_conversion_second
// valid return states: BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_READ_CONFIGURATION
bms_monitor_fsm_state_t bms_monitor_fsm_do_start_open_wire_pud_conversion_second(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_READ_CONFIGURATION;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_start_open_wire_conversion(LTC6810_2_PUP_INACTIVE), "ow_pud_conv_second");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_OPEN_WIRE_PUD_READ_CONFIGURATION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state open_wire_pud_read_configuration
// valid return states: BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_A
bms_monitor_fsm_state_t bms_monitor_fsm_do_open_wire_pud_read_configuration(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_A;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_configuration(), "ow_pud_read_configuration");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_A:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_open_wire_pud_a
// valid return states: BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_B
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_open_wire_pud_a(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_B;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_open_wire_voltages(BMS_MONITOR_VOLTAGE_REGISTER_A, BMS_MANAGER_OPEN_WIRE_OPERATION_PUD), "read_ow_pud_a");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_READ_OPEN_WIRE_PUD_B:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state read_open_wire_pud_b
// valid return states: BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION
bms_monitor_fsm_state_t bms_monitor_fsm_do_read_open_wire_pud_b(bms_monitor_fsm_state_data_t *data) {
    bms_monitor_fsm_state_t next_state = BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION;
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    BMS_MON_STEP(bms_monitor_api_read_open_wire_voltages(BMS_MONITOR_VOLTAGE_REGISTER_B, BMS_MANAGER_OPEN_WIRE_OPERATION_PUD), "read_ow_pud_b");

    switch (next_state) {
        case BMS_MONITOR_FSM_STATE_START_VOLT_CONVERSION:
            break;
        default:
            next_state = BMS_MONITOR_FSM_NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | |
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_|
 *
 *   __                  _   _
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from read_open_wire_pud_b to start_volt_conversion
void bms_monitor_fsm_check_open_wire(bms_monitor_fsm_state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);

    uint32_t open_wire = bms_monitor_api_check_open_wire();
    logger_api_log(LOGGER_LEVEL_DEBUG, "[MON] check_open_wire mask=0x%lx", (unsigned long)open_wire);
}

/*  ____  _        _
 * / ___|| |_ __ _| |_ ___
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *
 *
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|
 *                              |___/
 */

bms_monitor_fsm_state_t bms_monitor_fsm_run_state(bms_monitor_fsm_state_t cur_state, bms_monitor_fsm_state_data_t *data) {
    /* Printed BEFORE the state body runs: if a state's SPI transaction hangs,
       this is the last line you will see on the serial console. */
    logger_api_log(LOGGER_LEVEL_DEBUG, "[MON] %s", bms_monitor_fsm_state_names[cur_state]);

    bms_monitor_fsm_state_t new_state = bms_monitor_fsm_state_table[cur_state](data);
    if (new_state == BMS_MONITOR_FSM_NO_CHANGE)
        new_state = cur_state;

    bms_monitor_fsm_transition_func_t *transition = bms_monitor_fsm_transition_table[cur_state][new_state];
    if (transition)
        transition(data);

    return new_state;
}

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    bms_monitor_fsm_state_t cur_state = BMS_MONITOR_FSM_STATE_INIT;

    do {
        cur_state = bms_monitor_fsm_run_state(cur_state, NULL);
        sleep(1);

    } while (1);

    return 0;
}
#endif
