/******************************************************************************
Finite State Machine
Project: bms_monitor_fsm.dot
Description: gv_fsm example

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-07-29 07:16:04 +0200
Generated from: bms_monitor_fsm.dot
The finite state machine has:
  18 states
  1 transition functions

******************************************************************************/


#ifndef BMS_MONITOR_FSM_H
#define BMS_MONITOR_FSM_H
#ifdef __cplusplus
extern "C" {
#endif
#include <stdlib.h>

// State data object
// By default set to void; override this typedef or load the proper
// header if you need
typedef void state_data_t;

// NOTHING SHALL BE CHANGED AFTER THIS LINE!

// List of states
typedef enum {
  STATE_INIT = 0,  
  STATE_START_VOLT_CONVERTION,  
  STATE_VOLT_WRITE_CONFIGURATION,  
  STATE_VOLT_READ_CONFIGURATION,  
  STATE_READ_VOLT_A,  
  STATE_READ_VOLT_B,  
  STATE_START_OPEN_WIRE_PUP_CONVERTION_FIRST,  
  STATE_OPEN_WIRE_PUP_WRITE_CONFIGURATION,  
  STATE_START_OPEN_WIRE_PUP_CONVERTION_SECOND,  
  STATE_OPEN_WIRE_PUP_READ_CONFIGURATION,  
  STATE_READ_OPEN_WIRE_PUP_A,  
  STATE_READ_OPEN_WIRE_PUP_B,  
  STATE_START_OPEN_WIRE_PUD_CONVERTION_FIRST,  
  STATE_OPEN_WIRE_PUD_WRITE_CONFIGURATION,  
  STATE_START_OPEN_WIRE_PUD_CONVERTION_SECOND,  
  STATE_OPEN_WIRE_PUD_READ_CONFIGURATION,  
  STATE_READ_OPEN_WIRE_PUD_A,  
  STATE_READ_OPEN_WIRE_PUD_B,  
  NUM_STATES,
  NO_CHANGE
} state_t;

// State human-readable names
extern const char *bms_monitor_state_names[];

// State function and state transition prototypes
typedef state_t state_func_t(state_data_t *data);
typedef void transition_func_t(state_data_t *data);

// State functions
// Function to be executed in state init
// valid return states: STATE_START_VOLT_CONVERTION
state_t bms_monitor_do_init(state_data_t *data);
// Function to be executed in state start_volt_convertion
// valid return states: STATE_VOLT_WRITE_CONFIGURATION
state_t do_start_volt_convertion(state_data_t *data);
// Function to be executed in state volt_write_configuration
// valid return states: STATE_VOLT_READ_CONFIGURATION
state_t do_volt_write_configuration(state_data_t *data);
// Function to be executed in state volt_read_configuration
// valid return states: STATE_READ_VOLT_A
state_t do_volt_read_configuration(state_data_t *data);
// Function to be executed in state read_volt_a
// valid return states: STATE_READ_VOLT_B
state_t do_read_volt_a(state_data_t *data);
// Function to be executed in state read_volt_b
// valid return states: STATE_START_OPEN_WIRE_PUP_CONVERTION_FIRST
state_t do_read_volt_b(state_data_t *data);
// Function to be executed in state start_open_wire_pup_convertion_first
// valid return states: STATE_OPEN_WIRE_PUP_WRITE_CONFIGURATION
state_t do_start_open_wire_pup_convertion_first(state_data_t *data);
// Function to be executed in state open_wire_pup_write_configuration
// valid return states: STATE_START_OPEN_WIRE_PUP_CONVERTION_SECOND
state_t do_open_wire_pup_write_configuration(state_data_t *data);
// Function to be executed in state start_open_wire_pup_convertion_second
// valid return states: STATE_OPEN_WIRE_PUP_READ_CONFIGURATION
state_t do_start_open_wire_pup_convertion_second(state_data_t *data);
// Function to be executed in state open_wire_pup_read_configuration
// valid return states: STATE_READ_OPEN_WIRE_PUP_A
state_t do_open_wire_pup_read_configuration(state_data_t *data);
// Function to be executed in state read_open_wire_pup_a
// valid return states: STATE_READ_OPEN_WIRE_PUP_B
state_t do_read_open_wire_pup_a(state_data_t *data);
// Function to be executed in state read_open_wire_pup_b
// valid return states: STATE_START_OPEN_WIRE_PUD_CONVERTION_FIRST
state_t do_read_open_wire_pup_b(state_data_t *data);
// Function to be executed in state start_open_wire_pud_convertion_first
// valid return states: STATE_OPEN_WIRE_PUD_WRITE_CONFIGURATION
state_t do_start_open_wire_pud_convertion_first(state_data_t *data);
// Function to be executed in state open_wire_pud_write_configuration
// valid return states: STATE_START_OPEN_WIRE_PUD_CONVERTION_SECOND
state_t do_open_wire_pud_write_configuration(state_data_t *data);
// Function to be executed in state start_open_wire_pud_convertion_second
// valid return states: STATE_OPEN_WIRE_PUD_READ_CONFIGURATION
state_t do_start_open_wire_pud_convertion_second(state_data_t *data);
// Function to be executed in state open_wire_pud_read_configuration
// valid return states: STATE_READ_OPEN_WIRE_PUD_A
state_t do_open_wire_pud_read_configuration(state_data_t *data);
// Function to be executed in state read_open_wire_pud_a
// valid return states: STATE_READ_OPEN_WIRE_PUD_B
state_t do_read_open_wire_pud_a(state_data_t *data);
// Function to be executed in state read_open_wire_pud_b
// valid return states: STATE_START_VOLT_CONVERTION
state_t do_read_open_wire_pud_b(state_data_t *data);


// List of state functions
extern state_func_t *const bms_monitor_state_table[NUM_STATES];


// Transition functions
void check_open_wire(state_data_t *data);

// Table of transition functions
extern transition_func_t *const bms_monitor_transition_table[NUM_STATES][NUM_STATES];

// state manager
state_t bms_monitor_run_state(state_t cur_state, state_data_t *data);

#ifdef __cplusplus
}
#endif
#endif // BMS_MONITOR_FSM_H
