/******************************************************************************
Finite State Machine
Project: assets/fsm/fsm.dot
Description: gv_fsm example

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-04-27 14:29:37 +0200
Generated from: assets/fsm/fsm.dot
The finite state machine has:
  5 states
  10 transition functions

******************************************************************************/

#include "fsm.h"

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!
#include <stdint.h>

#include "eagletrt-api.h"
#include "bms-monitor-fsm.h"
#include "can-communication-api.h"
#include "identity-api.h"
#include "can-primary.h"
#include "post-api.h"
#include "eagletrt.h"
#include "post-api.h"
#include "post.h"
#include "logger-api.h"
#include "bms-monitor-api.h"
#include "voltage-api.h"
#include "temperature-api.h"
#include "feedback-api.h"
#include "defines.h"
#include "adc.h"

EAGLETRT_STATIC uint32_t last_tick = 0U;

constexpr uint32_t bms_monitor_fsm_run_delay = 2U;

EAGLETRT_STATIC bms_monitor_fsm_state_t bms_monitor_fsm_state = BMS_MONITOR_FSM_STATE_INIT;

EAGLETRT_STATIC void prv_periodically_send(enum CanPrimaryLvacfsmStatus status, uint32_t tick) {
    identity_api_periodically_send_state(status, tick);
    identity_api_periodically_send_version(tick);
    identity_api_periodically_send_libcan_version(tick);
}

/*!
 * \brief Print a compact human-readable snapshot of the board over the serial
 *        logger: per-cell voltages (mV), every NTC of the multiplexer (deci-°C),
 *        the analog rails (mV), the feedback statuses and the open-wire result.
 *
 * \note  The logger is built against nano.specs without floating-point printf
 *        support, so every value is formatted as an integer.
 */
EAGLETRT_STATIC void prv_print_debug(void) {
    volt voltages[DEFINES_CELLS_SERIES_COUNT] = { 0.F };
    (void)voltage_api_dump_voltages(voltages, 0U, DEFINES_CELLS_SERIES_COUNT);

    celsius temperatures[DEFINES_CELLS_NTC_COUNT] = { 0.F };
    (void)temperature_api_dump_temperatures(temperatures, 0U, DEFINES_CELLS_NTC_COUNT);

    const uint32_t open_wire = bms_monitor_api_check_open_wire();

    logger_api_log(LOGGER_LEVEL_INFO, "===== BMS (V=mV, T=dC, I=mA) =====");
    logger_api_log(LOGGER_LEVEL_INFO, "V %d %d %d %d %d %d", (int)(voltages[0] * 1000.F), (int)(voltages[1] * 1000.F), (int)(voltages[2] * 1000.F), (int)(voltages[3] * 1000.F), (int)(voltages[4] * 1000.F), (int)(voltages[5] * 1000.F));

    /* Every cell NTC comes from the MCU multiplexer: index n is mux channel n.
       The raw divider voltages are printed next to the temperatures because the
       NTC pull-up R59 is still unset on the schematic, so the volt-to-celsius
       curve cannot be trusted yet while the voltages can. */
    logger_api_log(LOGGER_LEVEL_INFO, "Tmin %d Tmax %d Tavg %d", (int)(temperature_api_get_min() * 10.F), (int)(temperature_api_get_max() * 10.F), (int)(temperature_api_get_average() * 10.F));
    logger_api_log(LOGGER_LEVEL_INFO, "T_MUX0-5 %d %d %d %d %d %d", (int)(temperatures[0] * 10.F), (int)(temperatures[1] * 10.F), (int)(temperatures[2] * 10.F), (int)(temperatures[3] * 10.F), (int)(temperatures[4] * 10.F), (int)(temperatures[5] * 10.F));
    logger_api_log(LOGGER_LEVEL_INFO, "T_MUX6-11 %d %d %d %d %d %d", (int)(temperatures[6] * 10.F), (int)(temperatures[7] * 10.F), (int)(temperatures[8] * 10.F), (int)(temperatures[9] * 10.F), (int)(temperatures[10] * 10.F), (int)(temperatures[11] * 10.F));
    logger_api_log(LOGGER_LEVEL_INFO, "NTCV0-5 %d %d %d %d %d %d", (int)(adc_get_ntc_voltage(0U) * 1000.F), (int)(adc_get_ntc_voltage(1U) * 1000.F), (int)(adc_get_ntc_voltage(2U) * 1000.F), (int)(adc_get_ntc_voltage(3U) * 1000.F), (int)(adc_get_ntc_voltage(4U) * 1000.F), (int)(adc_get_ntc_voltage(5U) * 1000.F));
    logger_api_log(LOGGER_LEVEL_INFO, "NTCV6-11 %d %d %d %d %d %d", (int)(adc_get_ntc_voltage(6U) * 1000.F), (int)(adc_get_ntc_voltage(7U) * 1000.F), (int)(adc_get_ntc_voltage(8U) * 1000.F), (int)(adc_get_ntc_voltage(9U) * 1000.F), (int)(adc_get_ntc_voltage(10U) * 1000.F), (int)(adc_get_ntc_voltage(11U) * 1000.F));

    logger_api_log(LOGGER_LEVEL_INFO, "MCU %d mux %d%s VDDA %d", (int)(adc_get_mcu_temperature() * 10.F), (int)adc_get_current_ntc_channel(), adc_is_mux_held() ? " HOLD" : "", (int)(adc_get_vdda() * 1000.F));
    logger_api_log(LOGGER_LEVEL_INFO, "VIN %d UNF %d VSUP %d", (int)(adc_get_vin() * 1000.F), (int)(adc_get_vin_unfused() * 1000.F), (int)(adc_get_vsup() * 1000.F));
    logger_api_log(LOGGER_LEVEL_INFO, "VOUT %d LVMS %d 5V %d", (int)(adc_get_vout() * 1000.F), (int)(adc_get_lvms_out() * 1000.F), (int)(adc_get_mcu_5v() * 1000.F));
    logger_api_log(LOGGER_LEVEL_INFO, "V_CHRG %d I_CHRG %d", (int)(adc_get_charger_voltage() * 1000.F), (int)(adc_get_charger_current() * 1000.F));
    /* No sensor drives I_OUT_SENSED, so only the node voltage means anything. */
    logger_api_log(LOGGER_LEVEL_INFO, "I_OUT_node %d (no sensor)", (int)(adc_get_i_out_sense_voltage() * 1000.F));

    /* The LTC auxiliary inputs carry the balancing/charger resistor NTCs, not
       cell NTCs, so they stay out of the temperature module and are shown raw. */
    logger_api_log(LOGGER_LEVEL_INFO, "TS_LTC %d %d %d %d", (int)(bms_monitor_api_get_gpio_voltage(0U) * 1000.F), (int)(bms_monitor_api_get_gpio_voltage(1U) * 1000.F), (int)(bms_monitor_api_get_gpio_voltage(2U) * 1000.F), (int)(bms_monitor_api_get_gpio_voltage(3U) * 1000.F));

    /* NTC channels that are open or shorted, one bit each, same shape as the
       cell open-wire mask. Those channels are left out of min/max/average. */
    logger_api_log(LOGGER_LEVEL_INFO, "NTCflt 0x%lx DCC 0x%x", (unsigned long)temperature_api_get_fault_bitmask(), (unsigned)bms_monitor_api_get_discharge());

    /* One digit per feedback, in enum Feedback order: 0 low, 1 error, 2 high. */
    logger_api_log(LOGGER_LEVEL_INFO, "FB %d%d%d%d%d%d%d%d", (int)feedback_api_get_status(FEEDBACK_SUPPLY_ENABLE_NEGATED), (int)feedback_api_get_status(FEEDBACK_SUPPLY_DELAY), (int)feedback_api_get_status(FEEDBACK_CHARGE_STATUS_NEGATED), (int)feedback_api_get_status(FEEDBACK_CHARGE_VIN_VALID_NEGATED), (int)feedback_api_get_status(FEEDBACK_OUTPUT_ENABLE_NEGATED), (int)feedback_api_get_status(FEEDBACK_OUTPUT_DELAY), (int)feedback_api_get_status(FEEDBACK_OUTPUT_FUSE), (int)feedback_api_get_status(FEEDBACK_VOUT));
    logger_api_log(LOGGER_LEVEL_INFO, "OpenWire 0x%lx %s", (unsigned long)open_wire, (open_wire == 0U) ? "none" : "DETECTED");
}

// GLOBALS
// State human-readable names
__attribute__((unused))
const char *state_names[] = { "init", "idle", "fatal", "flash", "balancing" };

// List of state functions
state_func_t *const state_table[NUM_STATES] = {
    do_init,      // in state init
    do_idle,      // in state idle
    do_fatal,     // in state fatal
    do_flash,     // in state flash
    do_balancing, // in state balancing
};

// Table of transition functions
transition_func_t *const transition_table[NUM_STATES][NUM_STATES] = {
    /* states:       init              , idle              , fatal             , flash             , balancing          */
    /* init      */ { NULL, init_to_idle, init_to_fatal, NULL, NULL },
    /* idle      */ { NULL, NULL, idle_to_fatal, idle_to_flash, idle_to_balancing },
    /* fatal     */ { NULL, NULL, NULL, fatal_to_flash, NULL },
    /* flash     */ { NULL, flash_to_idle, flash_to_fatal, NULL, NULL },
    /* balancing */ { NULL, balancing_to_idle, balancing_to_fatal, NULL, NULL },
};

/*  ____  _        _
 * / ___|| |_ __ _| |_ ___
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *
 *   __                  _   _
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: STATE_IDLE, STATE_FATAL
state_t do_init(state_data_t *data) {
    state_t next_state = STATE_IDLE;
    /* Your Code Here */
    struct PostInitData *fsm_init_data = (struct PostInitData *)data;

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM] do_init: running POST");
    const enum PostReturnCode post_rc = post_api_run(fsm_init_data);
    if (post_rc != POST_RC_OK) {
        logger_api_log(LOGGER_LEVEL_ERROR, "[FSM] POST failed rc=%d -> FATAL", (int)post_rc);
        next_state = STATE_FATAL;
    } else {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM] POST ok");
    }

    identity_api_send_state(CAN_PRIMARY_LVACFSM_STATUS_INIT);
    bms_monitor_fsm_state = bms_monitor_fsm_run_state(BMS_MONITOR_FSM_STATE_INIT, nullptr);
    logger_api_log(LOGGER_LEVEL_INFO, "[FSM] monitor fsm primed, state=%d", (int)bms_monitor_fsm_state);

    switch (next_state) {
        case STATE_IDLE:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_FLASH, STATE_IDLE, STATE_BALANCING, STATE_FATAL
state_t do_idle(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    struct FsmData *fsm_idle_data = (struct FsmData *)data;

    const uint32_t current_tick = fsm_idle_data->tick;

    can_communication_api_process_rx(CAN_COMMUNICATION_NETWORK_PRIMARY);

    /* Step the monitor FSM (cell voltages + open-wire) at its cadence. */
    if (current_tick - last_tick >= bms_monitor_fsm_run_delay) {
        last_tick = current_tick;

        bms_monitor_fsm_state = bms_monitor_fsm_run_state(bms_monitor_fsm_state, nullptr);
    }

    /* Serial debug interface at 1 Hz. */
    static uint32_t last_debug_tick = 0U;
    if (current_tick - last_debug_tick > 500U) {
        last_debug_tick = current_tick;
        prv_print_debug();
    }

    prv_periodically_send(CAN_PRIMARY_LVACFSM_STATUS_IDLE, current_tick);

    can_communication_api_process_tx(CAN_COMMUNICATION_NETWORK_PRIMARY);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_IDLE:
        case STATE_BALANCING:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state fatal
// valid return states: NO_CHANGE, STATE_FLASH, STATE_FATAL
state_t do_fatal(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    struct FsmData *fsm_idle_data = (struct FsmData *)data;

    const uint32_t current_tick = fsm_idle_data->tick;
    if (current_tick - last_tick >= bms_monitor_fsm_run_delay) {
        last_tick = current_tick;

        bms_monitor_fsm_state = bms_monitor_fsm_run_state(bms_monitor_fsm_state, nullptr);
    }

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: STATE_IDLE, STATE_FATAL
state_t do_flash(state_data_t *data) {
    state_t next_state = STATE_IDLE;
    /* Your Code Here */
    struct FsmData *fsm_idle_data = (struct FsmData *)data;

    const uint32_t current_tick = fsm_idle_data->tick;
    if (current_tick - last_tick >= bms_monitor_fsm_run_delay) {
        last_tick = current_tick;

        bms_monitor_fsm_state = bms_monitor_fsm_run_state(bms_monitor_fsm_state, nullptr);
    }

    switch (next_state) {
        case STATE_IDLE:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state balancing
// valid return states: NO_CHANGE, STATE_IDLE, STATE_BALANCING, STATE_FATAL
state_t do_balancing(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    struct FsmData *fsm_idle_data = (struct FsmData *)data;

    const uint32_t current_tick = fsm_idle_data->tick;
    if (current_tick - last_tick >= bms_monitor_fsm_run_delay) {
        last_tick = current_tick;

        bms_monitor_fsm_state = bms_monitor_fsm_run_state(bms_monitor_fsm_state, nullptr);
    }

    switch (next_state) {
        case NO_CHANGE:
        case STATE_IDLE:
        case STATE_BALANCING:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | |
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_|
 *
 *   __                  _   _
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from init to idle
void init_to_idle(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from init to fatal
void init_to_fatal(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from flash to idle
void flash_to_idle(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from flash to fatal
void flash_to_fatal(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from idle to flash
void idle_to_flash(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from idle to balancing
void idle_to_balancing(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from idle to fatal
void idle_to_fatal(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from balancing to idle
void balancing_to_idle(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from balancing to fatal
void balancing_to_fatal(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from fatal to flash
void fatal_to_flash(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

/*  ____  _        _
 * / ___|| |_ __ _| |_ ___
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *
 *
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|
 *                              |___/
 */

state_t run_state(state_t cur_state, state_data_t *data) {
    state_t new_state = state_table[cur_state](data);
    if (new_state == NO_CHANGE)
        new_state = cur_state;

    if (new_state != cur_state) {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM] %s -> %s", state_names[cur_state], state_names[new_state]);
    }

    transition_func_t *transition = transition_table[cur_state][new_state];
    if (transition) {
        transition(data);
    }

    return new_state;
}

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    state_t cur_state = STATE_INIT;

    do {
        cur_state = run_state(cur_state, NULL);
        sleep(1);

    } while (1);

    return 0;
}
#endif
