/******************************************************************************
Finite State Machine
Project: assets/fsm/fsm.dot
Description: gv_fsm example

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.2
Generation date: 2026-04-27 14:29:37 +0200
Generated from: assets/fsm/fsm.dot
The finite state machine has:
  5 states
  10 transition functions

******************************************************************************/

#include "fsm.h"

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!
#include <stdint.h>

#include "eagletrt-api.h"
#include "bms-monitor-fsm.h"
#include "identity-api.h"
#include "can-primary.h"
#include "post-api.h"
#include "eagletrt.h"
#include "post-api.h"
#include "post.h"
#include "logger-api.h"
#include "bms-monitor-api.h"
#include "voltage-api.h"
#include "temperature-api.h"
#include "defines.h"

EAGLETRT_STATIC uint32_t last_tick = 0U;

constexpr uint32_t bms_monitor_fsm_run_delay = 100U;

EAGLETRT_STATIC bms_monitor_fsm_state_t bms_monitor_fsm_state = BMS_MONITOR_FSM_STATE_INIT;

EAGLETRT_STATIC void prv_periodically_send(enum CanPrimaryLvacfsmStatus status, uint32_t tick) {
    identity_api_periodically_send_state(status, tick);
    identity_api_periodically_send_version(tick);
    identity_api_periodically_send_libcan_version(tick);
}

/*!
 * \brief Print a compact human-readable snapshot of the pack over the serial
 *        logger: per-cell voltages (mV), the LTC GPIO temperatures (deci-°C)
 *        and the open-wire status.
 *
 * \note  The logger is built against nano.specs without floating-point printf
 *        support, so every value is formatted as an integer.
 */
EAGLETRT_STATIC void prv_print_debug(void) {
    volt voltages[DEFINES_CELLS_SERIES_COUNT] = { 0.F };
    (void)voltage_api_dump_voltages(voltages, 0U, DEFINES_CELLS_SERIES_COUNT);

    celsius temperatures[DEFINES_LTC_GPIO_COUNT] = { 0.F };
    (void)temperature_api_dump_temperatures(temperatures, 0U, DEFINES_LTC_GPIO_COUNT);

    const uint32_t open_wire = bms_monitor_api_check_open_wire();

    logger_api_log(LOGGER_LEVEL_INFO, "===== BMS =====");
    logger_api_log(LOGGER_LEVEL_INFO, "V[mV] %d %d %d %d %d %d", (int)(voltages[0] * 1000.F), (int)(voltages[1] * 1000.F), (int)(voltages[2] * 1000.F), (int)(voltages[3] * 1000.F), (int)(voltages[4] * 1000.F), (int)(voltages[5] * 1000.F));
    logger_api_log(LOGGER_LEVEL_INFO, "T[dC] %d %d %d %d", (int)(temperatures[0] * 10.F), (int)(temperatures[1] * 10.F), (int)(temperatures[2] * 10.F), (int)(temperatures[3] * 10.F));
    logger_api_log(LOGGER_LEVEL_INFO, "OpenWire 0x%lx %s", (unsigned long)open_wire, (open_wire == 0U) ? "none" : "DETECTED");
}

// GLOBALS
// State human-readable names
__attribute__((unused))
const char *state_names[] = { "init", "idle", "fatal", "flash", "balancing" };

// List of state functions
state_func_t *const state_table[NUM_STATES] = {
    do_init,      // in state init
    do_idle,      // in state idle
    do_fatal,     // in state fatal
    do_flash,     // in state flash
    do_balancing, // in state balancing
};

// Table of transition functions
transition_func_t *const transition_table[NUM_STATES][NUM_STATES] = {
    /* states:       init              , idle              , fatal             , flash             , balancing          */
    /* init      */ { NULL, init_to_idle, init_to_fatal, NULL, NULL },
    /* idle      */ { NULL, NULL, idle_to_fatal, idle_to_flash, idle_to_balancing },
    /* fatal     */ { NULL, NULL, NULL, fatal_to_flash, NULL },
    /* flash     */ { NULL, flash_to_idle, flash_to_fatal, NULL, NULL },
    /* balancing */ { NULL, balancing_to_idle, balancing_to_fatal, NULL, NULL },
};

/*  ____  _        _
 * / ___|| |_ __ _| |_ ___
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *
 *   __                  _   _
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// Function to be executed in state init
// valid return states: STATE_IDLE, STATE_FATAL
state_t do_init(state_data_t *data) {
    state_t next_state = STATE_IDLE;
    /* Your Code Here */
    struct PostInitData *fsm_init_data = (struct PostInitData *)data;

    logger_api_log(LOGGER_LEVEL_INFO, "[FSM] do_init: running POST");
    const enum PostReturnCode post_rc = post_api_run(fsm_init_data);
    if (post_rc != POST_RC_OK) {
        logger_api_log(LOGGER_LEVEL_ERROR, "[FSM] POST failed rc=%d -> FATAL", (int)post_rc);
        next_state = STATE_FATAL;
    } else {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM] POST ok");
    }

    identity_api_send_state(CAN_PRIMARY_LVACFSM_STATUS_INIT);
    bms_monitor_fsm_state = bms_monitor_fsm_run_state(BMS_MONITOR_FSM_STATE_INIT, nullptr);
    logger_api_log(LOGGER_LEVEL_INFO, "[FSM] monitor fsm primed, state=%d", (int)bms_monitor_fsm_state);

    switch (next_state) {
        case STATE_IDLE:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state idle
// valid return states: NO_CHANGE, STATE_FLASH, STATE_IDLE, STATE_BALANCING, STATE_FATAL
state_t do_idle(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    struct FsmData *fsm_idle_data = (struct FsmData *)data;

    const uint32_t current_tick = fsm_idle_data->tick;

    /* Step the monitor FSM (cell voltages + open-wire) at its cadence. */
    if (current_tick - last_tick >= bms_monitor_fsm_run_delay) {
        last_tick = current_tick;

        bms_monitor_fsm_state = bms_monitor_fsm_run_state(bms_monitor_fsm_state, nullptr);
    }

    /* Acquire the 4 NTC temperatures from the LTC GPIOs. Two-phase: start the
       GPIO ADC (ADAX) on one tick, read it back (RDAUX) on the next, so the
       conversion has time to settle. */
    static uint32_t last_temp_tick = 0U;
    static bool temp_read_phase = false;
    if (current_tick - last_temp_tick >= 200U) {
        last_temp_tick = current_tick;
        if (temp_read_phase) {
            (void)bms_monitor_api_read_gpio_temperatures();
        } else {
            (void)bms_monitor_api_start_gpio_conversion();
        }
        temp_read_phase = !temp_read_phase;
    }

    /* Serial debug interface at 1 Hz. */
    static uint32_t last_debug_tick = 0U;
    if (current_tick - last_debug_tick >= 1000U) {
        last_debug_tick = current_tick;
        prv_print_debug();
    }

    prv_periodically_send(CAN_PRIMARY_LVACFSM_STATUS_IDLE, current_tick);

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_IDLE:
        case STATE_BALANCING:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state fatal
// valid return states: NO_CHANGE, STATE_FLASH, STATE_FATAL
state_t do_fatal(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    struct FsmData *fsm_idle_data = (struct FsmData *)data;

    const uint32_t current_tick = fsm_idle_data->tick;
    if (current_tick - last_tick >= bms_monitor_fsm_run_delay) {
        last_tick = current_tick;

        bms_monitor_fsm_state = bms_monitor_fsm_run_state(bms_monitor_fsm_state, nullptr);
    }

    switch (next_state) {
        case NO_CHANGE:
        case STATE_FLASH:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state flash
// valid return states: STATE_IDLE, STATE_FATAL
state_t do_flash(state_data_t *data) {
    state_t next_state = STATE_IDLE;
    /* Your Code Here */
    struct FsmData *fsm_idle_data = (struct FsmData *)data;

    const uint32_t current_tick = fsm_idle_data->tick;
    if (current_tick - last_tick >= bms_monitor_fsm_run_delay) {
        last_tick = current_tick;

        bms_monitor_fsm_state = bms_monitor_fsm_run_state(bms_monitor_fsm_state, nullptr);
    }

    switch (next_state) {
        case STATE_IDLE:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

// Function to be executed in state balancing
// valid return states: NO_CHANGE, STATE_IDLE, STATE_BALANCING, STATE_FATAL
state_t do_balancing(state_data_t *data) {
    state_t next_state = NO_CHANGE;
    /* Your Code Here */
    struct FsmData *fsm_idle_data = (struct FsmData *)data;

    const uint32_t current_tick = fsm_idle_data->tick;
    if (current_tick - last_tick >= bms_monitor_fsm_run_delay) {
        last_tick = current_tick;

        bms_monitor_fsm_state = bms_monitor_fsm_run_state(bms_monitor_fsm_state, nullptr);
    }

    switch (next_state) {
        case NO_CHANGE:
        case STATE_IDLE:
        case STATE_BALANCING:
        case STATE_FATAL:
            break;
        default:
            next_state = NO_CHANGE;
    }

    return next_state;
}

/*  _____                    _ _   _
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | |
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_|
 *
 *   __                  _   _
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */

// This function is called in 1 transition:
// 1. from init to idle
void init_to_idle(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from init to fatal
void init_to_fatal(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from flash to idle
void flash_to_idle(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from flash to fatal
void flash_to_fatal(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from idle to flash
void idle_to_flash(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from idle to balancing
void idle_to_balancing(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from idle to fatal
void idle_to_fatal(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from balancing to idle
void balancing_to_idle(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from balancing to fatal
void balancing_to_fatal(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

// This function is called in 1 transition:
// 1. from fatal to flash
void fatal_to_flash(state_data_t *data) {
    /* Your Code Here */
    EAGLETRT_API_UNUSED(data);
}

/*  ____  _        _
 * / ___|| |_ __ _| |_ ___
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *
 *
 *  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __
 * | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
 * | | | | | | (_| | | | | (_| | (_| |  __/ |
 * |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|
 *                              |___/
 */

state_t run_state(state_t cur_state, state_data_t *data) {
    state_t new_state = state_table[cur_state](data);
    if (new_state == NO_CHANGE)
        new_state = cur_state;

    if (new_state != cur_state) {
        logger_api_log(LOGGER_LEVEL_INFO, "[FSM] %s -> %s", state_names[cur_state], state_names[new_state]);
    }

    transition_func_t *transition = transition_table[cur_state][new_state];
    if (transition) {
        transition(data);
    }

    return new_state;
}

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
    state_t cur_state = STATE_INIT;

    do {
        cur_state = run_state(cur_state, NULL);
        sleep(1);

    } while (1);

    return 0;
}
#endif
